node:
  trigger:
    include: src/svelte-app/.gitlab-ci.yml
    strategy: depend
  rules:
    - when: always
go:
  trigger:
    include: src/go-rest-api/.gitlab-ci.yml
    strategy: depend
  rules:
    - when: always
