image: golang:1.19

cache:
  key: gocache
  paths:
    - vendor/go/pkg/mod/
    - vendor/cache
    - vendor/linter-cache

before_script:
  - cd src/go-rest-api

lint:
  stage: test
  image: golangci/golangci-lint
  script:
    - golangci-lint run -v --timeout=5m
  variables:
    GOCACHE: ${CI_PROJECT_DIR}/vendor/cache
    GOPATH: ${CI_PROJECT_DIR}/vendor/go
    GOLANGCI_LINT_CACHE: ${CI_PROJECT_DIR}/vendor/linter-cache

test:
  stage: test
  script: go test -v ./...

build:
  stage: build
  script: go build ./cmd/server/main.go
