image: golang:1.19

before_script: cd src/go-rest-api

lint:
  stage: test
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh |
      sh -s -- -b $(go env GOPATH)/bin v1.52.2
    - golangci-lint run

test:
  stage: test
  script: go test -v ./...
