image: golang:1.19

before_script: cd src/go-rest-api

lint:
  stage: test
  script:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2
    - golangci-lint run

test:
  stage: test
  script: go test -v ./...
