version: "3.9"

services:
  api:
    build: .
    image: plusvasis-api:latest
    container_name: plusvasis-api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plusvasis-api.entrypoints=https"
      - "traefik.http.routers.plusvasis-api.rule=Host(`api.plusvasis.xyz`)"
      - "traefik.http.services.plusvasis-api.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true
