version: "3.8"

services:
  api:
    container_name: plusvasis-api
    image: plusvasis-api:latest
    build: ./go-rest-api
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plusvasis-api.entrypoints=https"
      - "traefik.http.routers.plusvasis-api.rule=Host(`api.plusvasis.xyz`)"
      - "traefik.http.services.plusvasis-api.loadbalancer.server.port=8080"
    networks:
      - proxy
  app:
    container_name: plusvasis-app
    image: plusvasis-app:latest
    build: ./svelte-app
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plusvasis-app.entrypoints=https"
      - "traefik.http.routers.plusvasis-app.rule=Host(`app.plusvasis.xyz`)"
      - "traefik.http.services.plusvasis-app.loadbalancer.server.port=3000"
    networks:
      - proxy
    depends_on:
      - api

networks:
  proxy:
    external: true
